config/routes.rb
Rails.application.routes.draw do
<<<<<<< HEAD
  devise_for :admin_users, ActiveAdmin::Devise.config
  resources :object_tables
  resources :root_tables
  ActiveAdmin.routes(self)
  get "db" => "db#root_table"
=======
  
  resources :no_groups
  resources :doppelte_objects
  resources :root_externaldocuments
  resources :root_collections
  resources :root_objects
  get 'welcome/index'
  root 'welcome#index'
  resources :search_collections
  resources :imp_search_objects
  resources :object_tables
  resources :relassignproperties
  resources :relassignmeasures
  resources :relassignpropertywithvalues
  resources :relassignvalues
  resources :relassignunits
  resources :relsequences
  resources :typerelsequences
  resources :typevalues
  resources :values
  resources :measurewithunits
  resources :units
  resources :activities
  resources :actors
  resources :relassociates
  resources :typerelassociates
  resources :typecollections
  resources :reldocuments
  resources :relassigncollections
  resources :relationships
  resources :externaldocuments
  resources :relcollects
  resources :root_tables 
  resources :properties
  resources :subjects
  resources :collections
  resources :objlistendb4s
>>>>>>> 8e31398c502b5332a4908c846796eb04e6245ac6
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/collection.rb
class Collection < ApplicationRecord
    self.primary_key='guid'
<<<<<<< HEAD
    belongs_to :root_table, :optional => true
    has_and_belongs_to_many :object_tables, :optional => true
=======
    belongs_to :root_table, optional: true
    belongs_to :root_object, optional: true
    has_many :relassigncollections
>>>>>>> 8e31398c502b5332a4908c846796eb04e6245ac6
end

app/controllers/collections_controller.rb
class CollectionsController < ApplicationController
  before_action :set_collection, only: [:show, :edit, :update, :destroy]

  # GET /collections
  # GET /collections.json
  def index
    @collections = Collection.all
  end

  # GET /collections/1
  # GET /collections/1.json
  def show
  end

  # GET /collections/new
  def new
    @collection = Collection.new
  end

  # GET /collections/1/edit
  def edit
  end

  # POST /collections
  # POST /collections.json
  def create
    @collection = Collection.new(collection_params)

    respond_to do |format|
      if @collection.save
        format.html { redirect_to @collection, notice: 'Collection was successfully created.' }
        format.json { render :show, status: :created, location: @collection }
      else
        format.html { render :new }
        format.json { render json: @collection.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /collections/1
  # PATCH/PUT /collections/1.json
  def update
    respond_to do |format|
      if @collection.update(collection_params)
        format.html { redirect_to @collection, notice: 'Collection was successfully updated.' }
        format.json { render :show, status: :ok, location: @collection }
      else
        format.html { render :edit }
        format.json { render json: @collection.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /collections/1
  # DELETE /collections/1.json
  def destroy
    @collection.destroy
    respond_to do |format|
      format.html { redirect_to collections_url, notice: 'Collection was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_collection
      @collection = Collection.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def collection_params
      params.fetch(:collection, {})
    end
end

app/helpers/collections_helper.rb
module CollectionsHelper
end

app/views/collections/_form.html.erb
<%= form_with(model: collection, local: true) do |f| %>
  <% if collection.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(collection.errors.count, "error") %> prohibited this collection from being saved:</h2>

      <ul>
        <% collection.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
  <%= f.label :guid %>
  <%= f.text_field :guid %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/collections/edit.html.erb
<h1>Editing Collection</h1>

<%= render 'form', collection: @collection %>

<%= link_to 'Show', @collection %> |
<%= link_to 'Back', collections_path %>

app/views/collections/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Collections</h1>

<table>
  <thead>
    <tr>
      <th>Guid</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @collections.each do |collection| %>
      <tr>
        <td><%= collection.guid %></td>
        <td><%= link_to 'Show', collection %></td>
        <td><%= link_to 'Edit', edit_collection_path(collection) %></td>
        <td><%= link_to 'Destroy', collection, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Collection', new_collection_path %>

app/views/collections/new.html.erb
<h1>New Collection</h1>

<%= render 'form', collection: @collection %>

<%= link_to 'Back', collections_path %>

app/views/collections/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Guid:</strong>
  <%= @collection.guid %>
</p>

<%= link_to 'Edit', edit_collection_path(@collection) %> |
<%= link_to 'Back', collections_path %>