config/routes.rb
Rails.application.routes.draw do
<<<<<<< HEAD
  devise_for :admin_users, ActiveAdmin::Devise.config
  resources :object_tables
  resources :root_tables
  ActiveAdmin.routes(self)
  get "db" => "db#root_table"
=======
  
  resources :no_groups
  resources :doppelte_objects
  resources :root_externaldocuments
  resources :root_collections
  resources :root_objects
  get 'welcome/index'
  root 'welcome#index'
  resources :search_collections
  resources :imp_search_objects
  resources :object_tables
  resources :relassignproperties
  resources :relassignmeasures
  resources :relassignpropertywithvalues
  resources :relassignvalues
  resources :relassignunits
  resources :relsequences
  resources :typerelsequences
  resources :typevalues
  resources :values
  resources :measurewithunits
  resources :units
  resources :activities
  resources :actors
  resources :relassociates
  resources :typerelassociates
  resources :typecollections
  resources :reldocuments
  resources :relassigncollections
  resources :relationships
  resources :externaldocuments
  resources :relcollects
  resources :root_tables 
  resources :properties
  resources :subjects
  resources :collections
  resources :objlistendb4s
>>>>>>> 8e31398c502b5332a4908c846796eb04e6245ac6
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/root_object.rb
class RootObject < ApplicationRecord
    self.primary_key='guid'
    has_one :object_table, foreign_key: "guid"
    has_one :collection, foreign_key: "guid"
    accepts_nested_attributes_for :object_table

end

app/controllers/root_objects_controller.rb
class RootObjectsController < ApplicationController
  before_action :set_root_object, only: [:show, :edit, :update, :destroy]

  # GET /root_objects
  # GET /root_objects.json
  def index
    #@root_objects = RootTable.all
    #@root_objects = RootTable.joins("INNER JOIN object_tables ON root_tables.guid=object_tables.guid")
    @root_objects = RootTable.search_objects(params[:search_objects])
    #respond_to do |format|
    #  format.xlsx {
    #    response.headers[
    #      'Content-Disposition'
    #    ] = "attachment; filename='items.xlsx'"
    #  }
    #  format.html { render :index }
    #end
  end

  # GET /root_objects/1
  # GET /root_objects/1.json
  def show
    @root_objects = RootObject.find(params[:id])  
  end

  # GET /root_objects/new
  def new
    @root_object = RootObject.new
  end

  # GET /root_objects/1/edit
  def edit
  end

  # POST /root_objects
  # POST /root_objects.json
  def create
    @root_object = RootObject.new(root_object_params)

    respond_to do |format|
      if @root_object.save
        format.html { redirect_to @root_object, notice: 'Root object was successfully created.' }
        format.json { render :show, status: :created, location: @root_object }
      else
        format.html { render :new }
        format.json { render json: @root_object.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /root_objects/1
  # PATCH/PUT /root_objects/1.json
  def update
    respond_to do |format|
      if @root_object.update(root_object_params)
        format.html { redirect_to @root_object, notice: 'Root object was successfully updated.' }
        format.json { render :show, status: :ok, location: @root_object }
      else
        format.html { render :edit }
        format.json { render json: @root_object.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /root_objects/1
  # DELETE /root_objects/1.json
  def destroy
    @root_object.destroy
    respond_to do |format|
      format.html { redirect_to root_objects_url, notice: 'Root object was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_root_object
      @root_object = RootObject.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def root_object_params
      params.require(:root_object).permit(:guid, :name, :versiondate, :versionid, :description)
    end
end

app/helpers/root_objects_helper.rb
module RootObjectsHelper
end

app/views/root_objects/_form.html.erb
<%= form_with(model: root_object, local: true) do |form| %>
  <% if root_object.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(root_object.errors.count, "error") %> prohibited this root_object from being saved:</h2>

      <ul>
        <% root_object.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/root_objects/edit.html.erb
<h1>Editing Root Object</h1>

<%= render 'form', root_object: @root_object %>

<%= link_to 'Show', @root_object %> |
<%= link_to 'Back', root_objects_path %>

app/views/root_objects/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Fachobjekte</h1>
<br>
<%= form_tag root_objects_path, :method => 'get' do %>
  <%= text_field_tag :search_objects, params[:search_objects] %>
  <%= submit_tag "Suche" %>
<% end %>
<br>
<%= link_to 'Neuer Eintrag', new_root_table_path %>
<br>
<br>
<table>
  <colgroup>
       <col span="1" style="width: 26%;">
       <col span="1" style="width: 5%;">
       <col span="1" style="width: 5%;">
       <col span="1" style="width: 13%;">
       <col span="1" style="width: 3%;">
       <col span="1" style="width: 3%;">
       <col span="1" style="width: 3%;">
       <col span="1" style="width: 10%;">
       <col span="1" style="width: 3%;">
       <col span="1" style="width: 15%;">
  </colgroup>
  <thead>
    <tr>
      <%#= <th>Guid</th> #%>
      <th>Name</th>
      <th>Versiondate</th>
      <th>Versionid</th>
      <th>Description</th>
      <th colspan="3">Actions</th>
      <th colspan="2">Collections</th>
      <th>Documents</th>
    </tr>
    <style>
      th, td {
      border: 1px solid black;
      }
    </style>
  </thead>

  <tbody>
    <% @root_objects.each do |root_table| %>
      <tr>
        <%#= <td><%= root_table.guid #%></td> 
        <td><%= root_table.name %></td>
        <td><%= root_table.versiondate %></td>
        <td><%= root_table.versionid %></td>
        <td><%= root_table.description %></td>      
        <td><%= link_to 'Show', root_table_path(id: root_table.guid) %></td>
        <td><%= link_to 'Edit', edit_root_table_path(id: root_table.guid) %></td>
        <td><%= link_to 'Destroy', root_table_path(id: root_table.guid), method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td><%= root_table.collection %></td>
        <td><%= link_to 'Edit', edit_root_table_path(id: root_table.guid) %></td>
        <td><%= root_table.document %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br />
<div class="field">
<%= link_to 'Download as Excel', root_objects_path(request.parameters.merge({:format => :xlsx, :style => 'color:white;'})), :class => "excel"  %>
<br /></div>

<br>
<%= link_to 'Back', root_tables_path %>

app/views/root_objects/new.html.erb
<h1>New Root Object</h1>

<%= render 'form', root_object: @root_object %>

<%= link_to 'Back', root_objects_path %>

app/views/root_objects/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_root_object_path(@root_object) %> |
<%= link_to 'Back', root_objects_path %>