config/routes.rb
Rails.application.routes.draw do
<<<<<<< HEAD
  devise_for :admin_users, ActiveAdmin::Devise.config
  resources :object_tables
  resources :root_tables
  ActiveAdmin.routes(self)
  get "db" => "db#root_table"
=======
  
  resources :no_groups
  resources :doppelte_objects
  resources :root_externaldocuments
  resources :root_collections
  resources :root_objects
  get 'welcome/index'
  root 'welcome#index'
  resources :search_collections
  resources :imp_search_objects
  resources :object_tables
  resources :relassignproperties
  resources :relassignmeasures
  resources :relassignpropertywithvalues
  resources :relassignvalues
  resources :relassignunits
  resources :relsequences
  resources :typerelsequences
  resources :typevalues
  resources :values
  resources :measurewithunits
  resources :units
  resources :activities
  resources :actors
  resources :relassociates
  resources :typerelassociates
  resources :typecollections
  resources :reldocuments
  resources :relassigncollections
  resources :relationships
  resources :externaldocuments
  resources :relcollects
  resources :root_tables 
  resources :properties
  resources :subjects
  resources :collections
  resources :objlistendb4s
>>>>>>> 8e31398c502b5332a4908c846796eb04e6245ac6
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/typerelsequence.rb
class Typerelsequence < ApplicationRecord
    self.primary_key='guid'
end

app/controllers/typerelsequences_controller.rb
class TyperelsequencesController < ApplicationController
  before_action :set_typerelsequence, only: [:show, :edit, :update, :destroy]

  # GET /typerelsequences
  # GET /typerelsequences.json
  def index
    @typerelsequences = Typerelsequence.all
  end

  # GET /typerelsequences/1
  # GET /typerelsequences/1.json
  def show
  end

  # GET /typerelsequences/new
  def new
    @typerelsequence = Typerelsequence.new
  end

  # GET /typerelsequences/1/edit
  def edit
  end

  # POST /typerelsequences
  # POST /typerelsequences.json
  def create
    @typerelsequence = Typerelsequence.new(typerelsequence_params)

    respond_to do |format|
      if @typerelsequence.save
        format.html { redirect_to @typerelsequence, notice: 'Typerelsequence was successfully created.' }
        format.json { render :show, status: :created, location: @typerelsequence }
      else
        format.html { render :new }
        format.json { render json: @typerelsequence.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /typerelsequences/1
  # PATCH/PUT /typerelsequences/1.json
  def update
    respond_to do |format|
      if @typerelsequence.update(typerelsequence_params)
        format.html { redirect_to @typerelsequence, notice: 'Typerelsequence was successfully updated.' }
        format.json { render :show, status: :ok, location: @typerelsequence }
      else
        format.html { render :edit }
        format.json { render json: @typerelsequence.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /typerelsequences/1
  # DELETE /typerelsequences/1.json
  def destroy
    @typerelsequence.destroy
    respond_to do |format|
      format.html { redirect_to typerelsequences_url, notice: 'Typerelsequence was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_typerelsequence
      @typerelsequence = Typerelsequence.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def typerelsequence_params
      params.fetch(:typerelsequence, {})
    end
end

app/helpers/typerelsequences_helper.rb
module TyperelsequencesHelper
end

app/views/typerelsequences/_form.html.erb
<%= form_with(model: typerelsequence, local: true) do |form| %>
  <% if typerelsequence.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(typerelsequence.errors.count, "error") %> prohibited this typerelsequence from being saved:</h2>

      <ul>
        <% typerelsequence.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/typerelsequences/edit.html.erb
<h1>Editing Typerelsequence</h1>

<%= render 'form', typerelsequence: @typerelsequence %>

<%= link_to 'Show', @typerelsequence %> |
<%= link_to 'Back', typerelsequences_path %>

app/views/typerelsequences/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Typerelsequences</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @typerelsequences.each do |typerelsequence| %>
      <tr>
        <td><%= link_to 'Show', typerelsequence %></td>
        <td><%= link_to 'Edit', edit_typerelsequence_path(typerelsequence) %></td>
        <td><%= link_to 'Destroy', typerelsequence, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Typerelsequence', new_typerelsequence_path %>

app/views/typerelsequences/new.html.erb
<h1>New Typerelsequence</h1>

<%= render 'form', typerelsequence: @typerelsequence %>

<%= link_to 'Back', typerelsequences_path %>

app/views/typerelsequences/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_typerelsequence_path(@typerelsequence) %> |
<%= link_to 'Back', typerelsequences_path %>