config/routes.rb
Rails.application.routes.draw do
<<<<<<< HEAD
  devise_for :admin_users, ActiveAdmin::Devise.config
  resources :object_tables
  resources :root_tables
  ActiveAdmin.routes(self)
  get "db" => "db#root_table"
=======
  
  resources :no_groups
  resources :doppelte_objects
  resources :root_externaldocuments
  resources :root_collections
  resources :root_objects
  get 'welcome/index'
  root 'welcome#index'
  resources :search_collections
  resources :imp_search_objects
  resources :object_tables
  resources :relassignproperties
  resources :relassignmeasures
  resources :relassignpropertywithvalues
  resources :relassignvalues
  resources :relassignunits
  resources :relsequences
  resources :typerelsequences
  resources :typevalues
  resources :values
  resources :measurewithunits
  resources :units
  resources :activities
  resources :actors
  resources :relassociates
  resources :typerelassociates
  resources :typecollections
  resources :reldocuments
  resources :relassigncollections
  resources :relationships
  resources :externaldocuments
  resources :relcollects
  resources :root_tables 
  resources :properties
  resources :subjects
  resources :collections
  resources :objlistendb4s
>>>>>>> 8e31398c502b5332a4908c846796eb04e6245ac6
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/no_group.rb
class NoGroup < ApplicationRecord
    self.primary_key='guid'
end

app/controllers/no_groups_controller.rb
class NoGroupsController < ApplicationController
  before_action :set_no_group, only: [:show, :edit, :update, :destroy]

  # GET /no_groups
  # GET /no_groups.json
  def index
    @no_groups = RootTable.find_by_sql("SELECT DISTINCT r.guid, r.name, r.versiondate, r.versionid, r.description, r.collection, r.document
    FROM root_tables r, object_tables o
    WHERE r.guid=o.guid AND o.guid NOT IN (SELECT rac.guid_relobject FROM relassigncollections rac)")
    #respond_to do |format|
    #  format.xlsx {
    #    response.headers[
    #      'Content-Disposition'
    #    ] = "attachment; filename='items.xlsx'"
    #  }
    #  format.html { render :index }
    #end
  end

  # GET /no_groups/1
  # GET /no_groups/1.json
  def show
  end

  # GET /no_groups/new
  def new
    @no_group = NoGroup.new
  end

  # GET /no_groups/1/edit
  def edit
  end

  # POST /no_groups
  # POST /no_groups.json
  def create
    @no_group = NoGroup.new(no_group_params)

    respond_to do |format|
      if @no_group.save
        format.html { redirect_to @no_group, notice: 'No group was successfully created.' }
        format.json { render :show, status: :created, location: @no_group }
      else
        format.html { render :new }
        format.json { render json: @no_group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /no_groups/1
  # PATCH/PUT /no_groups/1.json
  def update
    respond_to do |format|
      if @no_group.update(no_group_params)
        format.html { redirect_to @no_group, notice: 'No group was successfully updated.' }
        format.json { render :show, status: :ok, location: @no_group }
      else
        format.html { render :edit }
        format.json { render json: @no_group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /no_groups/1
  # DELETE /no_groups/1.json
  def destroy
    @no_group.destroy
    respond_to do |format|
      format.html { redirect_to no_groups_url, notice: 'No group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_no_group
      @no_group = NoGroup.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def no_group_params
      params.fetch(:no_group, {})
    end
end

app/helpers/no_groups_helper.rb
module NoGroupsHelper
end

app/views/no_groups/_form.html.erb
<%= form_with(model: no_group, local: true) do |form| %>
  <% if no_group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(no_group.errors.count, "error") %> prohibited this no_group from being saved:</h2>

      <ul>
        <% no_group.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/no_groups/edit.html.erb
<h1>Editing No Group</h1>

<%= render 'form', no_group: @no_group %>

<%= link_to 'Show', @no_group %> |
<%= link_to 'Back', no_groups_path %>

app/views/no_groups/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Objekte ohne Gruppenzuordnung</h1>

<table>
  <colgroup>
       <col span="1" style="width: 26%;">
       <col span="1" style="width: 5%;">
       <col span="1" style="width: 5%;">
       <col span="1" style="width: 13%;">
       <col span="1" style="width: 3%;">
       <col span="1" style="width: 3%;">
       <col span="1" style="width: 3%;">
       <col span="1" style="width: 10%;">
       <col span="1" style="width: 3%;">
       <col span="1" style="width: 15%;">
  </colgroup>
  <thead>
    <%#= <th>Guid</th> #%>
      <th>Name</th>
      <th>Versiondate</th>
      <th>Versionid</th>
      <th>Description</th>
      <th colspan="3">Actions</th>
      <th colspan="2">Collections</th>
      <th>Documents</th>
    <style>
      th, td {
      border: 1px solid black;
      }
    </style>
  </thead>

  <tbody>
    <% @no_groups.each do |root_table| %>
      <tr>
        <%#= <td><%= root_table.guid #%></td> 
        <td><%= root_table.name %></td>
        <td><%= root_table.versiondate %></td>
        <td><%= root_table.versionid %></td>
        <td><%= root_table.description %></td>
        <td><%= link_to 'Show', root_table_path(id: root_table.guid)  %></td>        
        <td><%= link_to 'Edit', edit_root_table_path(id: root_table.guid) %></td>
        <td><%= link_to 'Destroy', root_table_path(id: root_table.guid), method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td><%= root_table.collection %></td>
        <td><%= link_to 'Edit', edit_root_table_path(id: root_table.guid) %></td>
        <td><%= root_table.document %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<div class="field">
<%= link_to 'Download as Excel', no_groups_path(request.parameters.merge({:format => :xlsx, :style => 'color:white;'})), :class => "excel"  %>
<br /></div>
<br />

<%= link_to 'Back', root_tables_path %>

app/views/no_groups/new.html.erb
<h1>New No Group</h1>

<%= render 'form', no_group: @no_group %>

<%= link_to 'Back', no_groups_path %>

app/views/no_groups/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_no_group_path(@no_group) %> |
<%= link_to 'Back', no_groups_path %>